phrase:
  access_token: PHRASE_ACCESS_TOKEN
  project_id: 5f687b20b5897ffc289ec24acef767da
  push:
    sources:
      - file: ./app/src/main/res/values/strings.xml
        params:
          file_format: xml
          locale_id: en-US
          update_translations: true
  pull:
    targets:
      - file: ./app/src/main/res/values/strings.xml
        params:
          file_format: xml
          locale_id: en-US
      - file: ./app/src/main/res/values-es-rUS/strings.xml
        params:
          file_format: xml
          locale_id: es-US
